### ISSUE TITLE
Why this this repo not forked from crosire/scripthookvdotnet?

### ISSUE THREAD

**Issue by justalemon** [Saltyq/ScriptHookRDR2DotNet#1]
I was wondering why this repository is not forked from [crosire/scripthookvdotnet](https://github.com/crosire/scripthookvdotnet/), considering that is a tweaked and stripped down version of the later.

This would help moving SHVDN and SHRDN commits from one repo to the other more easy by knowing the git commit changes and being recognized by software like GitKraken as a fork/derivate from SHVDN.

**Comment by Saltyq** [comment]
Because they are separate projects
It is ported from SHVDN but is not the same product.

**Comment by justalemon** [comment]
They are technically the same projects with different implementations for GTA V and RDR2. A fork is literally "a copy of a repository", so I don't see why not pressing fork to keep the git commit history is a bad idea.

**Comment by justalemon** [comment]
Also, there is also a legal problem considering that you released the entire code without contacting all of the contributors for permission change between Zlib and MIT.
