### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by Shtivi** [Saltyq/ScriptHookRDR2DotNet#10]
Hi,
When I try to compile the project I get the following error:
"The name `RDR2DN` does not exist in the current context", in several places such Native.cs, World.cs, Global.cs...
Am I missing something?

**Comment by slipzdev** [comment]
Go to output folder
copy ScriptHookRDRDotNet.asi
rename copy to ScriptHookRDRDotNet.dll

**Comment by Shtivi** [comment]
thanks
