### ISSUE TITLE
Reading Ped position

### ISSUE THREAD

**Issue by Bob74** [Saltyq/ScriptHookRDR2DotNet#2]
* ScriptHookRDR2: v1.0.1207.73
* ScriptHookRDRDotNet: release 1.0.4.1

I just can't find a correct way to read a ped's position.

Here is what I got so far:
```C#
// ScriptHookRDR2DotNet API
// => Returns (0 ,0, 0)
Vector3 pos = Game.Player.Character.Position;

// Same as source code:
// https://github.com/Saltyq/ScriptHookRDR2DotNet/blob/master/source/scripting_v3/RDR2/Entities/Entity.cs#L118
// => Returns (0 ,0, 0)
Vector3 pos = Function.Call<Vector3>(Hash.GET_ENTITY_COORDS, Handle, 0);

// Using InputArguments:
// => Returns (0 ,0, 0)
InputArgument in_Handle = new InputArgument(Game.Player.Character.Handle);
InputArgument in_Alive = new InputArgument(false);
Vector3 pos = Function.Call<Vector3>(Hash.GET_ENTITY_COORDS, in_Handle, in_Alive).ToString();


// Using InputArguments + OutputArgument:
// => Returns random values that keep on changing each tick.
// All 3 coordinates to the same value (ie: 2.802597E-45)
InputArgument in_Handle = new InputArgument(Game.Player.Character.Handle);
InputArgument in_Alive = new InputArgument(false);
OutputArgument out_Pos = new OutputArgument();
Function.Call(Hash.GET_ENTITY_COORDS, in_Handle, in_Alive, out_Pos);
Vector3 pos = out_Pos.GetResult<Vector3>();
```

Anyone know where this problem can come from?

**Comment by slipzdev** [comment]
Seems like vectors aren't returning from natives
Fixing

**Comment by slipzdev** [comment]
Memory offsets changed to fix future issues
GET_ENTITY_COORDS actually takes 3 args, the last one is required for anything to be returned from it

Updated Entity.Position in the API
These will be pushed in next update

**Comment by Bob74** [comment]
Hum I'm still having the same issues as before even with the new release (1.0.4.4).

I changed the reference in Visual Studio and put the new files inside RDR2 main folder (the console is working btw).

But it still gives me `(0, 0, 0)` using the API and random numbers using `OutputArgument`.

**Comment by slipzdev** [comment]
Just pushed out 1.0.4.5, turns out I wasnt setting Entity.Handle for each instance

**Comment by slipzdev** [comment]
https://github.com/Saltyq/ScriptHookRDR2DotNet/releases/tag/1.0.4.5
