### ISSUE TITLE
Accessing Pools

### ISSUE THREAD

**Issue by KyronicSpecs** [Saltyq/ScriptHookRDR2DotNet#4]
Hey so about the pools.. did the GTAV version search the memory for a pattern on where the handles are locates in memory?  The game crashed whenever the external function was called for pulling the data from memory such as GetAllPeds() figured it might be memory pointer issue, but cant do anything since it's using Blades Dll (right?)

**Comment by slipzdev** [comment]
World.GetAllPeds() relies solely on 
`
        [DllImport("ScriptHookRDR2.dll", ExactSpelling = true, EntryPoint = "?worldGetAllPeds@@YAHPEAHH@Z")]
        public static extern int getAllPeds(int[] arr, int arrSize); 
`

I've cleaned out all memory offsets from the source, so if there is a crash when calling GetAllPeds(), then it is a ScriptHook issue

Is there a dialog box that appears on crash? Saying something related to "worldGetAllPeds"?

**Comment by thatoneguy650** [comment]
World.GetAllPeds() is not crashing for me but it is returning 0 every time.

**Comment by KyronicSpecs** [comment]
Got it to work by :

```
 public static List<Ped> GetAllPeds()
        {
            List<Ped> pedList = new List<Ped>();

            int arraySize = 1024;
            int[] peds = new int[arraySize];
            int pedCount = worldGetAllPeds(peds, arraySize);

            for (int i = 0; i < pedCount; i++)
            {
                pedList.Add(new Ped(peds[i]));
            }

            return pedList; //Array.ConvertAll(peds, handle => new Ped(handle));
        }
```

**Comment by PourrezJ** [comment]
https://github.com/PourrezJ/ScriptHookRDR2DotNet/commit/7bd60509ede4e41322ab7ba8ec1ad766db0fe8d9
