### ISSUE TITLE
Why is the Console class commented out entirely?

### ISSUE THREAD

**Issue by XaeroDegreaz** [Saltyq/ScriptHookRDR2DotNet#5]
What's the best way to perform simple log-based debugging for our scripts? Print to sysout?

**Comment by slipzdev** [comment]
I started to implement console logging but didnt finish it before releasing important updates

The best way to log anything right now is writing to a file, IO.File specifically
You can find plenty of methods online that simplify the process of adding prefixes and time logging as well.
