### ISSUE TITLE
give weapon dosnt work

### ISSUE THREAD

**Issue by SungJJinKang** [Saltyq/ScriptHookRDR2DotNet#8]
ped1.GiveWeapon(RDR2.WeaponHash.MeleeCleaver, 0, true);
but ped equip weapon on left hand always.....

**Comment by jdwohlever** [comment]
Does this hook crash the game over time like Alexander Blades Scripthook does?
(I found that AB's Scripthook will crash the game after 30 minute to an hour almost every single time)
